management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: "Practice23"
  freemarker:
    expose-request-attributes: true

  datasource:
    url: jdbc:postgresql://localhost:5432/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_EMAIL}
    password: ${USER_PASSWORD}
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

